---
title: "UPDATE CONFIG"
date: 2022-02-04
---
title: Update Config
author: longbui98
email: admin123@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is mainly used for studying.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
